protected/modules/invoice/controllers/InvoiceController.php
<?php

class InvoiceController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		$Admin = "isset(Yii::app()->user->role) && (Yii::app()->user->role==='admin')";
		$User  = "isset(Yii::app()->user->role) && (Yii::app()->user->role==='user')";
            
        return array(
        	array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete','admin','fillcustomer','print','addcharge','deletecharge'),
				'users'=>array('@'),
                'expression'=>$User,
			),
            
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete','admin','fillcustomer','print','addcharge','deletecharge'),
				'users'=>array('@'),
                'expression'=>$Admin,
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Invoice;
		$modelCustomer=new Customer;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Invoice']))
		{
			$model->attributes=$_POST['Invoice'];

			// Si creamos un nuevo Customer hay que guardarlo
			if(strlen($model->CustomerID) == 0):
				$modelCustomer->attributes=$_POST['Customer'];
				if($modelCustomer->save()):
					$model->CustomerID = $modelCustomer->ID;
				endif;
			else:
				$modelCustomer = Customer::model()->findByPK($model->CustomerID);
				$modelCustomer->attributes=$_POST['Customer'];
				$modelCustomer->save();
			endif;
			
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
			'modelCustomer'=>$modelCustomer,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$modelCustomer = Customer::model()->findByPK($model->CustomerID);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Invoice']))
		{
			$model->attributes=$_POST['Invoice'];
			
			// Si creamos un nuevo Customer hay que guardarlo
			if(strlen($model->CustomerID) == 0) :
				$modelCustomer->attributes=$_POST['Customer'];
				if($modelCustomer->save()):
					$model->CustomerID = $modelCustomer->ID;
				endif;
			else :
				$modelCustomer = Customer::model()->findByPK($model->CustomerID);
				$modelCustomer->attributes=$_POST['Customer'];
				$modelCustomer->save();
			endif;
			
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
			'modelCustomer'=>$modelCustomer,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Invoice');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Invoice('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Invoice']))
			$model->attributes=$_GET['Invoice'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	public function actionFillCustomer()
	{
		$model = Customer::model()->findByPK($_POST["id"]);
		
		echo CJSON::encode($model);
	}
	
	/*
	 * Print invoice
	 */
	public function actionPrint($id)
	{
		$model = $this->loadModel($id);
		
		$criteria = new CDbCriteria();
		$criteria->condition = "UserID = :userid AND InvoiceID = :invoiceid";
		$criteria->params = array(':userid' => Yii::app()->user->ID, ':invoiceid' => $model->ID);
		$modelCharges = Charge::model()->findAll($criteria);
		
		// Print invoice
		set_time_limit(600);
    		
        # mPDF
        $pdf = Yii::app()->ePdf->mpdf('', 'A4', '','','','','','','','','P');

        $pdf->writeHTMLfooter=false;
        $pdf->writeHTMLheader=false;
        $pdf->DeflMargin=25;
        $pdf->DefrMargin=25;
        $pdf->tMargin=15;
        $pdf->bMargin=15;

        $pdf->w=297;   //manually set width
        $pdf->h=209.8; //manually set height
        
        $pdf->WriteHTML($this->renderPartial('_print', array('model'=>$model,'modelCharges'=>$modelCharges), true));
        
        # Outputs ready PDF
	    $pdf->Output('Factura_'.date("d/m/Y").'.pdf','D');
	}
	
	/**
	*	Add charge to Invoice
	*/
	public function actionAddCharge()
	{
		$invoiceID = $_POST["invoice"];
		$name = $_POST["charge"];
		$value = $_POST["value"];
		
		$model = new Charge;
		$model->InvoiceID = $invoiceID;
		$model->Text = $name;
		$model->Price = $value;
		$model->IVA = User::model()->findByPK(Yii::app()->user->ID)->IVA;
		$model->UserID = Yii::app()->user->ID;
		
		if($model->save()):
			$criteria = new CDbCriteria();
			$criteria->condition = "UserID = :userid AND InvoiceID = :invoiceid";
			$criteria->params = array(':userid' => Yii::app()->user->ID, ':invoiceid' => $invoiceID);
			
			$modelCharges = Charge::model()->findAll($criteria);
			
			foreach($modelCharges as $charge):
				echo "<p><span class='deleteCharge' id='". $charge->ID ."'>X</span>" . $charge->Text . " | " . str_replace('.',',',$charge->Price) . "&euro;</p>";
			endforeach;			
		else:
			var_dump($model->errors);	
		endif;
		
		echo '
		<script>
			$(".deleteCharge").click(function(){
			
				if(confirm("\u00bfSeguro que quieres eliminar este concepto?"))
				{
					var request = $.ajax({
			                url: "'.$this->createURL("invoice/deleteCharge").'",
			                type: "POST",
			                dataType: "html",
							data: {
								charge : $(this).attr("id"),
								invoice : '.$model->InvoiceID.'
							}
			        });
			
			        request.done(function(msg) {
			        		$("#concepts").html(msg);
			        });
			    }
			    
			});
		</script>
		';
			
	}
	
	/**
	*	Delete Charge from Invoice
	*/
	public function actionDeleteCharge()
	{
		$model = Charge::model()->findByPK($_POST["charge"]);
		$model->delete();
		
		$criteria = new CDbCriteria();
		$criteria->condition = "UserID = :userid AND InvoiceID = :invoiceid";
		$criteria->params = array(':userid' => Yii::app()->user->ID, ':invoiceid' => $_POST["invoice"]);
		
		$modelCharges = Charge::model()->findAll($criteria);
		
		foreach($modelCharges as $charge):
			echo "<p><span class='deleteCharge' id='". $charge->ID ."'>X</span>" . $charge->Text . " | " . str_replace('.',',',$charge->Price) . "&euro;</p>";
		endforeach;		
		
		echo '
		<script>
			$(".deleteCharge").click(function(){
			
				if(confirm("\u00bfSeguro que quieres eliminar este concepto?"))
				{
					var request = $.ajax({
			                url: "'.$this->createURL("invoice/deleteCharge").'",
			                type: "POST",
			                dataType: "html",
							data: {
								charge : $(this).attr("id"),
								invoice : '.$model->InvoiceID.'
							}
			        });
			
			        request.done(function(msg) {
			        		$("#concepts").html(msg);
			        });
			    }
			    
			});
		</script>
		';
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Invoice::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='invoice-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/invoice/controllers/SerieController.php
<?php

class SerieController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		$Admin = "isset(Yii::app()->user->role) && (Yii::app()->user->role==='admin')";
		$User  = "isset(Yii::app()->user->role) && (Yii::app()->user->role==='user')";
            
        return array(
        	array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete','admin'),
				'users'=>array('@'),
                'expression'=>$User,
			),
            
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete','admin'),
				'users'=>array('@'),
                'expression'=>$Admin,
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Serie;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Serie']))
		{
			$model->attributes=$_POST['Serie'];
			
			// Si es predeterminada desmarcamos el resto y marcamos esta
			if($model->Pred == 1):
				$criteria = new CDbCriteria();
				$criteria->condition = "UserID = :userid";
				$criteria->params = array(':userid' => Yii::app()->user->ID);
				
				$modelSeries = Serie::model()->findAll($criteria);
				
				foreach($modelSeries as $serie):
					$laSerie = Serie::model()->findByPK($serie->ID);
					$laSerie->Pred = 0;
					$laSerie->save();
				endforeach;
			endif;
				
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Serie']))
		{
			$model->attributes=$_POST['Serie'];
			
			// Si es predeterminada desmarcamos el resto y marcamos esta
			if($model->Pred == 1):
				$criteria = new CDbCriteria();
				$criteria->condition = "UserID = :userid";
				$criteria->params = array(':userid' => Yii::app()->user->ID);
				
				$modelSeries = Serie::model()->findAll($criteria);
				
				foreach($modelSeries as $serie):
					$laSerie = Serie::model()->findByPK($serie->ID);
					$laSerie->Pred = 0;
					$laSerie->save();
				endforeach;
			endif;
			
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Serie');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Serie('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Serie']))
			$model->attributes=$_GET['Serie'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Serie::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='serie-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/invoice/views/invoice/_print.php
<style>
	table
{
	border-collapse: collapse;
}

table td
{
	padding: 10px;
}

table .supertitle
{
	font-size: 16pt;
	font-weight: bold;
	text-align: left;
}

table .title
{
	width: 10%;
	font-size: 11pt;
	font-weight: bold;
	text-align: left;
}

table .content
{
	font-size: 10pt;
	font-weight: normal;
	text-align: left;
}

table.borderer td
{
	border: 1px solid #333;
	padding: 10px;
}

</style>

<table cellspacing="0" cellpadding="8" style="border: 1px solid #333;width:100%;">

	<tr><td colspan="2" class="supertitle">Datos del cliente</td><td colspan="2" class="supertitle">Datos establecimiento</td></tr>
	
	<tr>
		<td class="title">DNI/NIF: </td><td class="content"><?php echo $model->customer->DNI; ?></td>
		<td class="title">DNI/NIF: </td><td class="content"><?php echo $model->user->DNI; ?></td>
	</tr>
	
	<tr>
		<td class="title">Nombre: </td><td class="content"><?php echo $model->customer->FullName; ?></td>
		<td class="title">Nombre: </td><td class="content"><?php echo $model->user->name; ?></td>
	</tr>
	
	<tr>
		<td class="title">Direcci&oacute;n: </td><td class="content"><?php echo $model->customer->Address; ?></td>
		<td class="title">Direcci&oacute;n: </td><td class="content"><?php echo $model->user->address; ?></td>
	</tr>

</table><br />

<table cellspacing="0" cellpadding="8" class="borderer conceptos" style="border: 1px solid #333;width:100%;">

	<tr><td colspan="2" class="supertitle">Conceptos</td></tr>
	
	<tr>
		<td class="title" style="width: 80%;">Detalle</td>
		<td class="title" style="text-align: center; width: 20%;">Precio</td>
	</tr>
		
	<?php foreach($modelCharges as $item): ?>
		<tr>
			<td class="content"><?php echo $item->Text; ?></td>
			<td class="content" style="text-align: center;"><?php echo str_replace('.',',',$item->Price); ?></td>
		</tr>
		
		<?php $total = $total + $item->Price; ?>
		
		<?php
			$iva = $iva + (($item->Price * $item->IVA)/100);
		?>
		
		
	<?php endforeach; ?>

</table><br />

<table cellspacing="0" cellpadding="8" class="borderer total" style="border: 1px solid #333;width:100%;">
	<tr>
		<td class="title" style="text-align: right; width: 80%;">IVA: </td>
		<td class="content" style="text-align: center; width: 20%;">
			<?php echo number_format($iva, 2); ?>
		</td>
	</tr>
	
	<tr>
		<td class="title" style="text-align: right; width: 80%;">TOTAL: </td>
		<td class="content" style="text-align: center; width: 20%; font-size: 14pt;">
			<?php echo number_format($total + $iva, 2); ?>&euro;
		</td>
	</tr>

</table><br />

protected/modules/invoice/views/invoice/admin.php
<?php
/* @var $this InvoiceController */
/* @var $model Invoice */

$this->breadcrumbs=array(
	'Facturas'=>array('admin'),
	'Listado',
);

$this->menu=array(
	array('label'=>'Nueva Factura', 'url'=>array('create')),
	array('label'=>'Nueva Serie', 'url'=>array('serie/create')),
	array('label'=>'Listado de series', 'url'=>array('serie/admin')),
);

?>

<h1 class="header">Listado de facturas</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'invoice-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'afterAjaxUpdate'=>"function(){
							jQuery('#date_Date').datepicker(jQuery.extend({showMonthAfterYear:false}, jQuery.datepicker.regional['es'], {'dateFormat':'yy-mm-dd'}));
						}",
	'columns'=>array(
		array(
            'name'=> 'SerieID',
            'value' => '$data->serie->Serie',
	        'filter' => CHtml::listData(Serie::model()->findAll(), 'ID', 'Serie'),
            'headerHtmlOptions'=>array(
                'style'=>'width:10%;text-align:left !important;',
            ),
            'htmlOptions'=>array(
                'style'=>'width:10%;text-align:left;',
            ),
        ),
		array(
            'name'=> 'Number',
            'filter'=> CHtml::activeTextField($model, 'Number', 
                 			array('placeholder'=>'Escribe el valor a buscar...')),
            'headerHtmlOptions'=>array(
                'style'=>'width:15%;text-align:left !important;',
            ),
            'htmlOptions'=>array(
                'style'=>'width:15%;text-align:left;',
            ),
        ),
		array(
            'name'=> 'CustomerID',
            'value' => '$data->customer->FullName',
	        'filter' => CHtml::listData(Customer::model()->findAll(), 'ID', 'FullName'),
            'headerHtmlOptions'=>array(
                'style'=>'width:50%;text-align:left !important;',
            ),
            'htmlOptions'=>array(
                'style'=>'width:50%;text-align:left;',
            ),
        ),
        array('name' => 'Date', 'filter'=>false, 'value'=>'date("d-m-Y", strtotime($data->Date))'),
		array(	
	        'class'=>'CButtonColumn',
	        'template'=>'{update} {delete}',
	        'buttons' => array(
	            'update' => array(
	            	'label' => 'Editar',
	            	'imageUrl' => Yii::app()->baseURL . '/images/edit.png',
	            ),
	            'delete' => array(
	            	'label' => 'Borrar',
	                'imageUrl' => Yii::app()->baseURL . '/images/delete.png',
	            ),
	        ),
	        'deleteConfirmation'=>'Si aceptas eliminaras este registro definitivamente.',
	    ),
	),
	'emptyText' => 'No hay registros. <a href="'.$this->createURL('create').'">Picha</a> para crear uno.',
    'summaryText' => 'Mostrando del {start} al {end} de {count} registro(s).',
)); 

protected/modules/invoice/views/invoice/create.php
<?php
/* @var $this InvoiceController */
/* @var $model Invoice */

$this->breadcrumbs=array(
	'Facturas'=>array('admin'),
	'Nueva factura',
);

$this->menu=array(
	array('label'=>'Listado de facturas', 'url'=>array('admin')),
	array('label'=>'Nueva Serie', 'url'=>array('serie/create')),
	array('label'=>'Listado de series', 'url'=>array('serie/admin')),
);
?>

<h1 class="header">Crear nueva factura</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model,'modelCustomer'=>$modelCustomer,)); ?>

protected/modules/invoice/views/invoice/update.php
<?php
/* @var $this InvoiceController */
/* @var $model Invoice */

$this->breadcrumbs=array(
	'Facturas'=>array('admin'),
	'Modificar',
);

$this->menu=array(
	array('label'=>'Listado de facturas', 'url'=>array('admin')),
	array('label'=>'Nueva Serie', 'url'=>array('serie/create')),
	array('label'=>'Listado de series', 'url'=>array('serie/admin')),
);
?>

<h1 class="header">Modificar factura</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model,'modelCustomer'=>$modelCustomer,)); ?>